labs:
  - id: S1
    base_score: 0
    dds_acceptance: []
    dds_readiness: []
  - id: S2
    base_score: 0
    dds_acceptance: []
    dds_readiness: []
  - id: S3
    base_score: 0
    dds_acceptance: []
    dds_readiness: []
  - id: S4
    base_score: 0
    dds_acceptance: []
    dds_readiness: []
  - id: T1
    base_score: 0
    dds_acceptance: []
    dds_readiness: []
  - id: T2
    base_score: 0
    dds_acceptance: []
    dds_readiness: []
  - id: T3
    base_score: 0
    dds_acceptance: []
    dds_readiness: []
  - id: T4
    base_score: 0
    dds_acceptance: []
    dds_readiness: []